- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- name: zsh | install and config
  block:
      - name: zsh | install zsh
        tags: zsh,shell
        become: true
        package:
            name:
                - zsh

      - name: zsh | chsh for user {{ ansible_user_id }}
        tags: zsh,shell
        become: true
        user:
            name: "{{ ansible_user_id }}"
            shell: /bin/zsh

      - name: zsh | create .config/zsh directories
        tags: zsh,shell,config
        ansible.builtin.file:
            path: "{{ item }}
            state: directory
        with_items:
          - "{{ ansible_user_dir }}/.config/zsh"
          - "{{ ansible_user_dir }}/.config/zsh/plugins"
          - "{{ ansible_user_dir }}/.config/zsh/plugins/zsh-autosuggestions"

      - name: zsh | copy ZSH configuration files
        tags: zsh,shell
        ansible.builtin.copy:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            owner: "{{ ansible_user_id }}"
            group: "{{ ansible_user_gid }}"
            mode: 0644
        with_items:
            - { src: 'zshrc', dest: '{{ ansible_user_dir }}/.zshrc' }
            - { src: 'zshenv', dest: '{{ ansible_user_dir }}/.config/zsh/zshenv'}
            - { src: 'zshalias', dest: '{{ ansible_user_dir }}/.config/zsh/alias.zsh'}
            - { src: 'zshfuncs', dest: '{{ ansible_user_dir }}/.config/zsh/funcs.zsh'}
            - { src: 'zshcompletion', dest: '{{ ansible_user_dir }}/.config/zsh/completion.zsh'}
            - { src: 'zshprompt', dest: '{{ ansible_user_dir }}/.config/zsh/base_prompt.zsh'}
            - { src: 'zshpowerline', dest: '{{ ansible_user_dir }}/.config/zsh/gimlab_prompt.zsh'}
            - { src: 'p10kzsh', dest: '{{ ansible_user_dir }}/.config/zsh/p10k.zsh'}
            - { src: 'zsh-autosuggestions.plugin.zsh', dest: '{{ ansible_user_dir }}/.config/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh'}
            - { src: 'zsh-autosuggestions.zsh', dest: '{{ ansible_user_dir }}/.config/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh'}

      - name: zsh | install powerline10k
        tags: zsh,themes
        ansible.builtin.git:
          repo: https://github.com/romkatv/powerlevel10k.git
          dest: "{{ ansible_user_dir }}/.config/zsh/powerlevel10k"
          depth: 1

  rescue:
      - set_fact: task_failed=true

