monitor=,preferred,auto,1

$terminal = foot
$menu = wofi --show drun
$editor = nvim

source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/startup.conf

general {
  gaps_in = 4
  gaps_out = 8
  border_size = 2
  col.active_border = rgba(89b4faee) rgba(cba6f7ee) 45deg
  col.inactive_border = rgba(45475aaa)
  layout = dwindle
}

decoration {
  rounding = 8
  blur { enabled = true; size = 6; passes = 2 }
  drop_shadow = true
  shadow_range = 8
  shadow_render_power = 2
}

animations {
  enabled = true
  bezier = easeOut, 0.05, 0.9, 0.1, 1.05
  animation = windows, 1, 5, easeOut
  animation = fade, 1, 5, default
  animation = workspaces, 1, 6, default
}

input {
  kb_layout = es
  follow_mouse = 1
  sensitivity = 0
  touchpad {
    natural_scroll = true
    tap-to-click = true
  }
}

dwindle {
  pseudotile = true
  preserve_split = true
}

misc {
  force_default_wallpaper = 0
  disable_hyprland_logo = true
}

windowrulev2 = float, class:^(pavucontrol)$
windowrulev2 = float, class:^(nm-connection-editor)$
