hwdec=auto
vo=gpu
profile=gpu-hq
scale=ewa_lanczos
cscale=ewa_lanczos
video-sync=display-resample
interpolation
tscale=oversample
keep-open=yes
save-position-on-quit=yes
osc=yes
osd-font-size=32
sub-auto=fuzzy
