# Load full config
# Simplify your bash PATH management
# From: http://www.moosechips.com/2011/01/bash-pathmunge/
EGREP=`type -p egrep`
pathmunge () {
        if ! echo $PATH | $EGREP -q "(^|:)$1($|:)" ; then
           if [ "$2" = "after" ] ; then
              PATH=$PATH:$1
           else
              PATH=$1:$PATH
           fi
        fi
}

function handle_error () {
  if [ "$?" != "0" ]; then
    echo -e "\n\n$1"
  fi
}

function load_and_handle_errors () {
    source "$1" 2>&1
    handle_error "${failure}There was a problem while sourcing ${component}$1\n\n\t${information}$SOURCE_OUTPUT${text_reset}"
}

# Set initial PATH
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
if [[ -d "$HOME/bin" ]]; then
  pathmunge $HOME/bin
fi

# Load colors
load_and_handle_errors $HOME/.bashrc.d/colors.bash

echo -e "${notice}Proceeding to load environment${text_reset}"
for f in $HOME/.bashrc.d/*.bash; do
  if [[ "$f" == "$HOME/.bashrc.d/colors.bash" ]]; then continue; fi
  load_and_handle_errors $f
done
unset f

# Load a last file with user config, if it exist
if [ -r $HOME/.bashrc.d/lastrc ]; then
  load_and_handle_errors $HOME/.bashrc.d/lastrc
fi

echo -n ${text_reset}

