" loading pathogen at runtime as it's bundled
runtime bundle/vim-pathogen/autoload/pathogen.vim
call pathogen#infect()
Helptags 

" Add GOPATH to vim path
set path +=$GOPATH/src/**

filetype plugin indent on

"Set Mapleader 
let mapleader = "," 
let g:mapleader = "," 

" We want syntax colorize
syntax on
set nocompatible        " Disable vi-compatibility
set laststatus=2        " Always show the statusline 
set nobackup
set nowritebackup
set notimeout
set ttimeout
set ttimeoutlen=10
set noswapfile
set encoding=utf-8      " Necessary to show unicode glyphs
set history=50
set ruler               " show the cursor position all the time
set showcmd             " display incomplete commands
set incsearch           " do incremental searching
set hlsearch
set ignorecase
set smartcase
set smartindent
set laststatus=2        " Always display the status line
set backspace=2         " Make backspace work
set autoread
set hidden
set vb t_vb="           " Disable virtual bell
set nu
set textwidth=0         " No annoying word wrapping
set tabstop=2
set shiftwidth=2
set expandtab
set nocp
set t_Co=256            " Explicitly tell vim that the terminal supports 256 colors
set cursorline          " highlight current line
" Session options for version greater than 7
if version >= 700
  set sessionoptions=blank,buffers,curdir,folds,globals,help,localoptions,options,resize,tabpages,winsize,winpos
endif

" Fix backspace
set backspace=indent,eol,start
fixdel

" Toggle paste mode
set pastetoggle=<F2>

" Send more characters for redraws
set ttyfast

" Use Bash as shell
set shell=/usr/local/bin/bash

" Enable mouse use in all modes
set mouse=a
set ttymouse=xterm2

" Display extra whitespace
set list listchars=tab:»·,trail:·
" Clipboard fix for OsX
"set clipboard=unnamed
" Don't do it inside tmux or
" it do not past with simple p (but ""p)
if $TMUX == ''
  set clipboard+=unnamed
endif

" Numbers
set number
set numberwidth=2

"Folding
set foldmethod=indent
set foldlevelstart=99

" Autocompletion options
set wildmode=list:longest,list:full
set complete=.,w,b

" Tags
let Tlist_Ctags_Cmd = "/usr/local/bin/ctags -R --exclude=.git --exclude=log -f ./.tags *"
set tags+=.tags

"Theme 
"let g:solarized_termcolors=256
"if has('gui_running')
"    set background=light
"else
"    set background=dark
"endif
"colorscheme solarized
colorscheme vividchalk

set guifont="Liberation Mono":h10

" Bring Bufferlist easily
map bl :Bufferlist<CR>

"NERDTree
map <Leader>, :NERDTreeToggle<cr>

map <Leader>f :b#<cr>            "Buffer shortcuts
map <Leader>c :let @/ = ""<cr>

filetype on
filetype plugin indent on

" Replaced by clang_complete for now
" autocmd FileType c set omnifunc=ccomplete#CompleteCpp
autocmd FileType ChangeLog set tw=80

source $HOME/.vim/functions.vim
source $HOME/.vim/autocommands.vim
source $HOME/.vim/shortcuts.vim



