- name: nnn | add apt repository
  tags: nnn
  ansible.builtin.apt_repository:
    repo: http://download.opensuse.org/repositories/home:/stig124:/nnn/xUbuntu_20.04/
    update_cache: yes
    filename: nnn

  - name: nnn | install nnn
  tags: nnn
  apt:
    update_cache: yes
    state: latest
    pkg:
      - nnn

#echo 'deb http://download.opensuse.org/repositories/home:/stig124:/nnn/xUbuntu_20.04/ /' | sudo tee /etc/apt/sources.list.d/home:stig124:nnn.list
#curl -fsSL https://download.opensuse.org/repositories/home:stig124:nnn/xUbuntu_20.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_stig124_nnn.gpg > /dev/null
