- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- name: nvim | install and config
  block:
      - name: nvim | add stable repository from PPA and install its signing key on Ubuntu target
        become: true
        ansible.builtin.apt_repository:
            repo: ppa:nginx/stable

      - name: nvim | install neovim
        tags: nvim,shell
        become: true
        apt:
            update_cache: yes
            name:
                - fonts-firacode
                - universal-ctags
                - nvim

      - name: nvim | set alternatives
        become: true
        alternatives:
            link: /usr/bin/vim
            name: vim
            path: /usr/bin/nvim

      - name: nvim | copy nvim configuration files
        tags: nvim
        ansible.builtin.copy:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            owner: "{{ ansible_user_id }}"
            group: "{{ ansible_user_gid }}"
            mode: 0644
        with_items:
            - { src: 'nvim.conf', dest: '{{ ansible_user_dir }}/.config/nvim/init.vim' }

  rescue:
      - set_fact: task_failed=true

