- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- name: nvim | install and config
  block:
      - name: nvim | create directories .config/nvim/lua dir
        tags: nvim,config
        file:
          path: "{{ ansible_user_dir }}/{{ item }}"
          state: directory
        with_items:
          - ".config/nvim/lua"
          - ".config/nvim/lua/pluginsConfig"
          - ".local/share/fonts"

      - name: nvim | install patched nerd font
        ansible.builtin.unarchive:
          src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/JetBrainsMono.zip
          dest: "{{ ansible_user_dir }}/.local/share/fonts"
          remote_src: yes

      - name: nvim | update fonts cache
        command: fc-cache -f

      - name: nvim | add stable repository from PPA and install its signing key on Ubuntu target
        tags: nvim
        become: true
        ansible.builtin.apt_repository:
            repo: ppa:neovim-ppa/unstable
            update_cache: yes

      - name: nvim | install neovim
        tags: nvim
        become: true
        apt:
            update_cache: yes
            state: latest
            pkg:
                - software-properties-common
                - universal-ctags
                - python3-dev
                - python3-pip
                - python3-neovim
                - neovim

      - name: nvim | set alternatives
        tags: nvim
        become: true
        community.general.alternatives:
            link: /usr/bin/vim
            name: vim
            path: /usr/bin/nvim

      - name: nvim | set alternatives
        tags: nvim
        become: true
        community.general.alternatives:
            link: /usr/bin/vi
            name: vi
            path: /usr/bin/nvim

      - name: nvim | set alternatives
        tags: nvim
        become: true
        community.general.alternatives:
            link: /usr/bin/editor
            name: editor
            path: /usr/bin/nvim

      - name: nvim | copy nvim configuration files
        tags: nvim
        ansible.builtin.copy:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            owner: "{{ ansible_user_id }}"
            group: "{{ ansible_user_gid }}"
            mode: 0644
        with_items:
            - { src: 'init.lua', dest: '{{ ansible_user_dir }}/.config/nvim/init.lua' }
            - { src: 'lua/autocommands.lua', dest: '{{ ansible_user_dir }}/.config/nvim/lua/autocommands.lua' }
            - { src: 'lua/basic.lua', dest: '{{ ansible_user_dir }}/.config/nvim/lua/basic.lua' }
            - { src: 'lua/lightline.lua', dest: '{{ ansible_user_dir }}/.config/nvim/lua/lightline.lua' }
            - { src: 'lua/maps.lua', dest: '{{ ansible_user_dir }}/.config/nvim/lua/maps.lua' }
            - { src: 'lua/plugins.lua', dest: '{{ ansible_user_dir }}/.config/nvim/lua/plugins.lua' }
            - { src: 'lua/plugin-nvim-tree.lua', dest: '{{ ansible_user_dir }}/.config/nvim/lua/pluginsConfig/nvim-tree.lua' }
            - { src: 'lua/plugin-telescope.lua', dest: '{{ ansible_user_dir }}/.config/nvim/lua/pluginsConfig/telescope.lua' }
            - { src: 'lua/plugin-bufferline.lua', dest: '{{ ansible_user_dir }}/.config/nvim/lua/pluginsConfig/bufferline.lua' }
            - { src: 'lua/plugin-autopairs.lua', dest: '{{ ansible_user_dir }}/.config/nvim/lua/pluginsConfig/autopairs.lua' }
            - { src: 'lua/plugin-lspinstall.lua', dest: '{{ ansible_user_dir }}/.config/nvim/lua/pluginsConfig/lspinstall.lua' }

      - name: nvim | install plugins
        command: vim +packerinstall +packercompile +qall

      - name: nvim | install language servers (npm)
        tags: nvim,lsp
        become: true
        community.general.npm:
          name: "{{ item }}"
          state: latest
          global: yes
        loop:
          - bash-language-server
          - typescript
          - typescript-language-server
          - graphql-language-service-cli
          - vscode-langservers-extracted
          - dockerfile-language-server-nodejs
          - yaml-language-server

      - name: Add an Apt signing key, uses whichever key is at the URL
        become: true
        ansible.builtin.apt_key:
          url: https://apt.releases.hashicorp.com/gpg
          state: present

      - name: nvim | add lsp repository for terraform
        become: true
        ansible.builtin.apt_repository:
          repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
          state: present

      - name: nvim | install language servers (apt)
        tags: nvim,lsp
        become: true
        apt:
            update_cache: yes
            state: latest
            pkg:
                - clangd-12
                - terraform-ls

      - name: nvim | set alternatives
        tags: nvim,lsp
        become: true
        community.general.alternatives:
          link: /usr/bin/clangd
          name: clangd
          path: /usr/bin/clangd-12
          priority: 100

      - name: nvim | install language servers (go install)
        become: true
        ansible.builtin.command: "go install {{ item }}"
        loop:
          - golang.org/x/tools/gopls@latest
          - github.com/lighttiger2505/sqls

      - name: nvim | activate language servers in nvim
        become: true
        ansible.builtin.command: "nvim --headless -c 'LspInstall {{ item }}' -c 'qall'"
        loop:
          - bash
          - cpp
          - dockerfile
          - html
          - json
          - typescript
          - go
          - graphql
          - terraform
          - yaml
          #- elixir - java - python - rust

  rescue:
      - set_fact: task_failed=true

